export const matchesData = [
  {
    id: "match-1",
    format: "T20",
    time: "3:30 PM IST",
    teamA: {
      name: "Mumbai Indians",
      stats: {
        wins: 8,
        losses: 3,
        winRate: 73,
        avgScore: 165,
        recentForm: "4W-1L",
        ranking: 1,
        keyPlayersCount: 5,
      },
      players: [
        { name: "Rohit Sharma", role: "Batsman" },
        { name: "Jasprit Bumrah", role: "Bowler" },
        { name: "Suryakumar Yadav", role: "All-rounder" },
        { name: "Hardik Pandya", role: "All-rounder" },
        { name: "Ishan Kishan", role: "Keeper" },
        { name: "Tilak Varma", role: "Batsman" },
        { name: "Piyush Chawla", role: "Bowler" },
        { name: "Cameron Green", role: "All-rounder" },
        { name: "Dewald Brevis", role: "Batsman" },
      ],
    },
    teamB: {
      name: "Delhi Capitals",
      stats: {
        wins: 7,
        losses: 4,
        winRate: 64,
        avgScore: 158,
        recentForm: "3W-2L",
        ranking: 3,
        keyPlayersCount: 4,
      },
      players: [
        { name: "David Warner", role: "Batsman" },
        { name: "Axar Patel", role: "All-rounder" },
        { name: "Rishabh Pant", role: "Keeper" },
        { name: "Prithvi Shaw", role: "Batsman" },
        { name: "Khaleel Ahmed", role: "Bowler" },
        { name: "Kuldeep Yadav", role: "Bowler" },
        { name: "Mitchell Marsh", role: "All-rounder" },
        { name: "Sarfaraz Khan", role: "Batsman" },
        { name: "Amogh Charitha", role: "Bowler" },
      ],
    },
    stadium: {
      name: "Wankhede Stadium",
      location: "Mumbai, India",
      capacity: "33,108",
      pitchType: "Hard Surface",
    },
    prediction: {
      winner: "Mumbai Indians",
      winProbability: "55%",
      confidence: "High",
      scoreRange: "165-175",
    },
  },
  // {
  //   id: "match-2",
  //   format: "ODI",
  //   time: "2:00 PM IST",
  //   teamA: {
  //     name: "India",
  //     stats: {
  //       wins: 12,
  //       losses: 2,
  //       winRate: 86,
  //       avgScore: 285,
  //       recentForm: "5W",
  //       ranking: 1,
  //       keyPlayersCount: 6,
  //     },
  //     players: [
  //       { name: "Virat Kohli", role: "Batsman" },
  //       { name: "Rohit Sharma", role: "Batsman" },
  //       { name: "Mohammed Shami", role: "Bowler" },
  //       { name: "Hardik Pandya", role: "All-rounder" },
  //       { name: "KL Rahul", role: "Batsman" },
  //       { name: "Ravindra Jadeja", role: "All-rounder" },
  //       { name: "Siraj Md", role: "Bowler" },
  //       { name: "Bumrah J", role: "Bowler" },
  //       { name: "Gill S", role: "Batsman" },
  //     ],
  //   },
  //   teamB: {
  //     name: "England",
  //     stats: {
  //       wins: 9,
  //       losses: 4,
  //       winRate: 69,
  //       avgScore: 265,
  //       recentForm: "3W-2L",
  //       ranking: 4,
  //       keyPlayersCount: 5,
  //     },
  //     players: [
  //       { name: "Joe Root", role: "Batsman" },
  //       { name: "Harry Brook", role: "Batsman" },
  //       { name: "Jofra Archer", role: "Bowler" },
  //       { name: "Ben Stokes", role: "All-rounder" },
  //       { name: "Dawid Malan", role: "Batsman" },
  //       { name: "Chris Woakes", role: "All-rounder" },
  //       { name: "Mark Wood", role: "Bowler" },
  //       { name: "Sam Curran", role: "All-rounder" },
  //       { name: "Will Jacks", role: "Batsman" },
  //     ],
  //   },
  //   stadium: {
  //     name: "Eden Gardens",
  //     location: "Kolkata, India",
  //     capacity: "66,349",
  //     pitchType: "Grass",
  //   },
  //   prediction: {
  //     winner: "India",
  //     winProbability: "62%",
  //     confidence: "High",
  //     scoreRange: "280-295",
  //   },
  // },
  // {
  //   id: "match-3",
  //   format: "Test",
  //   time: "9:30 AM IST",
  //   teamA: {
  //     name: "Australia",
  //     stats: {
  //       wins: 5,
  //       losses: 2,
  //       winRate: 71,
  //       avgScore: 420,
  //       recentForm: "3W-1L",
  //       ranking: 2,
  //       keyPlayersCount: 5,
  //     },
  //     players: [
  //       { name: "Steve Smith", role: "Batsman" },
  //       { name: "David Warner", role: "Batsman" },
  //       { name: "Pat Cummins", role: "Bowler" },
  //       { name: "Nathan Lyon", role: "Bowler" },
  //       { name: "Cameron Green", role: "All-rounder" },
  //       { name: "Travis Head", role: "Batsman" },
  //       { name: "Mitchell Starc", role: "Bowler" },
  //       { name: "Josh Hazlewood", role: "Bowler" },
  //       { name: "Alex Carey", role: "Keeper" },
  //     ],
  //   },
  //   teamB: {
  //     name: "South Africa",
  //     stats: {
  //       wins: 4,
  //       losses: 3,
  //       winRate: 57,
  //       avgScore: 410,
  //       recentForm: "2W-2L",
  //       ranking: 5,
  //       keyPlayersCount: 4,
  //     },
  //     players: [
  //       { name: "Dean Elgar", role: "Batsman" },
  //       { name: "Temba Bavuma", role: "Batsman" },
  //       { name: "Kagiso Rabada", role: "Bowler" },
  //       { name: "Marco Jansen", role: "All-rounder" },
  //       { name: "Kyle Verreynne", role: "Keeper" },
  //       { name: "Lizaad Williams", role: "Bowler" },
  //       { name: "Khaya Zondo", role: "Batsman" },
  //       { name: "Lungi Ngidi", role: "Bowler" },
  //       { name: "Keshav Maharaj", role: "Bowler" },
  //     ],
  //   },
  //   stadium: {
  //     name: "MCG",
  //     location: "Melbourne, Australia",
  //     capacity: "100,024",
  //     pitchType: "Hard Surface",
  //   },
  //   prediction: {
  //     winner: "Australia",
  //     winProbability: "58%",
  //     confidence: "Medium",
  //     scoreRange: "400-430",
  //   },
  // },
  {
    id: "match-4",
    format: "T20",
    time: "7:00 PM IST",
    teamA: {
      name: "Kolkata Knight Riders",
      stats: {
        wins: 6,
        losses: 5,
        winRate: 55,
        avgScore: 162,
        recentForm: "2W-3L",
        ranking: 5,
        keyPlayersCount: 4,
      },
      players: [
        { name: "Shreyas Iyer", role: "Batsman" },
        { name: "Phil Salt", role: "Batsman" },
        { name: "Sunil Narine", role: "Bowler" },
        { name: "Varun Chakaravarthy", role: "Bowler" },
        { name: "Andre Russell", role: "All-rounder" },
        { name: "Rinku Singh", role: "Batsman" },
        { name: "Harshit Rana", role: "Bowler" },
        { name: "Ramandeep Singh", role: "All-rounder" },
        { name: "Rahmanullah Gurbaz", role: "Keeper" },
      ],
    },
    teamB: {
      name: "Rajasthan Royals",
      stats: {
        wins: 7,
        losses: 4,
        winRate: 64,
        avgScore: 168,
        recentForm: "4W-2L",
        ranking: 2,
        keyPlayersCount: 5,
      },
      players: [
        { name: "Sanju Samson", role: "Keeper" },
        { name: "Yashasvi Jaiswal", role: "Batsman" },
        { name: "Riyan Parag", role: "All-rounder" },
        { name: "Trent Boult", role: "Bowler" },
        { name: "Yuzvendra Chahal", role: "Bowler" },
        { name: "Devdutt Padikkal", role: "Batsman" },
        { name: "Shimron Hetmyer", role: "Batsman" },
        { name: "Navdeep Saini", role: "Bowler" },
        { name: "Sandeep Sharma", role: "Bowler" },
      ],
    },
    stadium: {
      name: "Eden Gardens",
      location: "Kolkata, India",
      capacity: "66,349",
      pitchType: "Grass",
    },
    prediction: {
      winner: "Rajasthan Royals",
      winProbability: "60%",
      confidence: "High",
      scoreRange: "165-175",
    },
  },
  {
    id: "match-5",
    format: "T20",
    time: "5:00 PM IST",
    teamA: {
      name: "Chennai Super Kings",
      stats: {
        wins: 9,
        losses: 2,
        winRate: 82,
        avgScore: 170,
        recentForm: "5W",
        ranking: 1,
        keyPlayersCount: 6,
      },
      players: [
        { name: "MS Dhoni", role: "Keeper" },
        { name: "Ruturaj Gaikwad", role: "Batsman" },
        { name: "Rachin Ravindra", role: "Batsman" },
        { name: "Deepak Chahar", role: "Bowler" },
        { name: "Tushar Deshpande", role: "Bowler" },
        { name: "Moeen Ali", role: "All-rounder" },
        { name: "Shivam Dube", role: "All-rounder" },
        { name: "Simarjit Singh", role: "Bowler" },
        { name: "Devon Conway", role: "Batsman" },
      ],
    },
    teamB: {
      name: "Sunrisers Hyderabad",
      stats: {
        wins: 5,
        losses: 6,
        winRate: 45,
        avgScore: 158,
        recentForm: "1W-3L",
        ranking: 8,
        keyPlayersCount: 3,
      },
      players: [
        { name: "Aiden Markram", role: "Batsman" },
        { name: "Travis Head", role: "Batsman" },
        { name: "Bhuvneshwar Kumar", role: "Bowler" },
        { name: "Marco Jansen", role: "All-rounder" },
        { name: "T Natarajan", role: "Bowler" },
        { name: "Heinrich Klaasen", role: "Keeper" },
        { name: "Abdul Samad", role: "Batsman" },
        { name: "Mayank Markande", role: "Bowler" },
        { name: "Shahbaz Ahmed", role: "All-rounder" },
      ],
    },
    stadium: {
      name: "MA Chidambaram Stadium",
      location: "Chennai, India",
      capacity: "38,797",
      pitchType: "Batting-friendly",
    },
    prediction: {
      winner: "Chennai Super Kings",
      winProbability: "68%",
      confidence: "High",
      scoreRange: "170-185",
    },
  },
  // {
  //   id: "match-6",
  //   format: "ODI",
  //   time: "3:00 PM IST",
  //   teamA: {
  //     name: "Pakistan",
  //     stats: {
  //       wins: 6,
  //       losses: 5,
  //       winRate: 55,
  //       avgScore: 260,
  //       recentForm: "2W-3L",
  //       ranking: 6,
  //       keyPlayersCount: 4,
  //     },
  //     players: [
  //       { name: "Babar Azam", role: "Batsman" },
  //       { name: "Mohammad Rizwan", role: "Keeper" },
  //       { name: "Shaheen Afridi", role: "Bowler" },
  //       { name: "Fakhar Zaman", role: "Batsman" },
  //       { name: "Hassan Ali", role: "Bowler" },
  //       { name: "Shadab Khan", role: "All-rounder" },
  //       { name: "Hasan Raza", role: "Batsman" },
  //       { name: "Naseem Shah", role: "Bowler" },
  //       { name: "Iftikhar Ahmed", role: "All-rounder" },
  //     ],
  //   },
  //   teamB: {
  //     name: "West Indies",
  //     stats: {
  //       wins: 4,
  //       losses: 7,
  //       winRate: 36,
  //       avgScore: 245,
  //       recentForm: "1W-2L",
  //       ranking: 9,
  //       keyPlayersCount: 3,
  //     },
  //     players: [
  //       { name: "Brandon King", role: "Batsman" },
  //       { name: "Nicholas Pooran", role: "Keeper" },
  //       { name: "Alzarri Joseph", role: "Bowler" },
  //       { name: "Jason Holder", role: "All-rounder" },
  //       { name: "Akeal Hosein", role: "Bowler" },
  //       { name: "Alick Athanaze", role: "Batsman" },
  //       { name: "Roston Chase", role: "All-rounder" },
  //       { name: "Romesh Shepherd", role: "Bowler" },
  //       { name: "Jermaine Blackwood", role: "Batsman" },
  //     ],
  //   },
  //   stadium: {
  //     name: "National Stadium",
  //     location: "Karachi, Pakistan",
  //     capacity: "34,228",
  //     pitchType: "Batting-friendly",
  //   },
  //   prediction: {
  //     winner: "Pakistan",
  //     winProbability: "59%",
  //     confidence: "Medium",
  //     scoreRange: "260-280",
  //   },
  // },
]
